import React, {useEffect, useRef} from "react";
import Layout from "../../../layout/website";
import Section from "../../../layout/global/Section";
import Container from "../../../layout/global/Container";
import { Link } from "react-router-dom";
import { PaperAirplaneIcon } from "@heroicons/react/24/outline";
import { StarIcon } from "@heroicons/react/24/solid";
import { Breadcrumbs, Input } from "../../../components";
import Logo from "../../../layout/global/Logo";
import { useTheme } from "../../../layout/provider";

function TermsPage() {
    const theme = useTheme();
    return (
        <Layout title="Terms">
            <Section className="py-16 md:py-20 bg-slate-100 dark:bg-slate-950">
                <Container>
                    <div className="flex flex-col items-center justify-center">
                        <div className="w-full md:w-5/12">
                            <div className="text-center">
                                <h2 className="text-3xl font-bold text-slate-700 dark:text-white mb-2">
                                    Terms and Conditions
                                </h2>
                                <Breadcrumbs
                                    items={[
                                        { text: "Home", link: "/" },
                                        { text: "Terms" },
                                    ]}
                                />
                            </div>
                        </div>
                    </div>
                </Container>
                <div className="absolute h-[1px] w-full bottom-0 start-0 bg-gradient-to-r from-transparent from-10% via-blue-100 dark:via-blue-950 to-transparent to-90% animate-[animateGradient_5s_ease-in-out_2]"></div>
            </Section>

            <Section className="pt-16 md:pt-20 lg:pt-24 xl:pt-28 pb-2 bg-white dark:bg-slate-900 overflow-hidden">
                <Container>
                    <div class="mx-auto max-w-3xl">
                        <p class="text-sm italic text-slate-500 pb-3">Last updated: 23 Aug 2024</p>
                        <div class="prose dark:prose-invert prose-headings:font-bold prose-p:mt-2 prose-ul:mt-2 max-w-max">
                            <p>Welcome to Scribbler! These Terms and Conditions ("Terms") govern your use of our AI content generator application (the "App") and any related services (collectively, the "Services"). Please read these Terms carefully before using the App.</p>
                            <h6>1. Acceptance of Terms</h6>
                            <p>By accessing or using our Services, you agree to be bound by these Terms. If you do not agree with any part of these Terms, you may not use the Services.</p>
                            <h6>2. Eligibility</h6>
                            <p>You must be at least 18 years old to use the App. By using the Services, you represent and warrant that you meet this eligibility requirement.</p>
                            <h6>3. User Accounts</h6>
                            <p>To access certain features of the App, you may need to create an account. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.</p>
                            <h6>4. Use of the Services</h6>
                            <ul>
                            <li>You agree to use the Services only for lawful purposes and in accordance with these Terms.</li>
                            <li>You must not use the App to create, share, or distribute content that is illegal, harmful, offensive, or violates the rights of others.</li>
                            <li>You are responsible for ensuring that any content you generate using the App complies with applicable laws and regulations.</li>
                            </ul>
                            <h6>5. Intellectual Property</h6>
                            <ul>
                            <li>All intellectual property rights in the App and the content generated by the AI, excluding user-provided content, are owned by Scribbler.AI.</li>
                            <li>You retain ownership of any content you input into the App. However, by using the Services, you grant Scribbler.AI a worldwide, non-exclusive, royalty-free license to use, store, and process your content to provide the Services.</li>
                            </ul>
                            <h6>6. Content Usage and Ownership</h6>
                            <ul>
                            <li>The AI-generated content may be used for personal, educational, or commercial purposes, subject to these Terms.</li>
                            <li>You acknowledge that the content generated by the App may contain errors or inaccuracies and should be reviewed before use. Scribbler.AI is not liable for any damages arising from the use of AI-generated content.</li>
                            </ul>
                            <h6>7. Payment and Subscription</h6>
                            <ul>
                            <li>Some features of the App may require payment of fees. If you choose to subscribe to a paid plan, you agree to pay all applicable fees and taxes.</li>
                            <li>Payments are non-refundable, except as required by law or as otherwise stated in our refund policy.</li>
                            </ul>
                            <h6>8. Termination</h6>
                            <ul>
                            <li>We may terminate or suspend your access to the App at any time, without notice, if you breach these Terms or for any other reason.</li>
                            <li>You may terminate your account at any time by following the instructions in the App. Upon termination, your right to use the Services will immediately cease.</li>
                            </ul>
                            <h6>9. Disclaimers</h6>
                            <ul>
                            <li>The Services are provided "as is" and "as available" without any warranties, express or implied. Scribbler.AI does not guarantee that the Services will be error-free, secure, or uninterrupted.</li>
                            <li>Scribbler.AI is not responsible for any damages or losses resulting from your use of the App.</li>
                            </ul>
                            <h6>10. Limitation of Liability</h6>
                            <p>To the fullest extent permitted by law, Scribbler.AI shall not be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the Services.</p>
                            <h6>11. Indemnification</h6>
                            <p>You agree to indemnify and hold harmless Scribbler.AI, its affiliates, and their respective directors, officers, employees, and agents from any claims, damages, liabilities, and expenses arising from your use of the App or any breach of these Terms.</p>
                            <h6>12. Changes to the Terms</h6>
                            <p>We may update these Terms from time to time. If we make material changes, we will notify you by email or through the App. Your continued use of the Services after any changes constitute your acceptance of the new Terms.</p>
                            <h6>13. Governing Law</h6>
                            <p>These Terms are governed by and construed in accordance with the laws of USA, without regard to its conflict of law principles.</p>
                            <h6>14. Contact Us</h6>
                            <p>If you have any questions about these Terms, please contact us at [Your Contact Information].</p>
                        </div>
                    </div>
                </Container>
            </Section>
            <Section className="pt-16 md:pt-20 lg:pt-24 xl:pt-28 bg-white dark:bg-slate-900 overflow-hidden">
                <Container>
                    <div className="relative bg-gradient-to-b from-white to-slate-50 dark:from-slate-900 dark:to-slate-950 border border-b-0 border-gray-200 dark:border-gray-800 rounded-t-xl p-6 sm:p-10 !pb-0">
                        <div className="flex flex-wrap items-center -m-4">
                            <div className="p-4 w-full lg:w-6/12">
                                <div className="lg:pb-10">
                                    <h1 className="text-2xl sm:text-4xl/snug font-bold text-slate-700 dark:text-white mb-4">Revolutionize Your Copywriting Save <span className="bg-gradient-to-r from-indigo-500 to-blue-500 bg-clip-text text-transparent">Time and Money</span></h1>
                                    <p className="text-slate-500 dark:text-slate-300 text-base/relaxed sm:text-lg/relaxed mb-6">Stop the drain on your resources and start investing your time and money where it truly matters.</p>
                                    <button className="inline-flex justify-center font-bold text-base bg-blue-600 text-white hover:bg-blue-800 transition-all px-7 py-3 rounded-lg">
                                        Try it for Free
                                    </button>
                                </div>
                            </div>
                            
                            <div className="p-4 w-full lg:w-6/12 self-end">
                                <img className="rounded-t-xl shadow-lg shadow-blue-100 dark:shadow-blue-950 border border-b-0 border-gray-200 dark:border-gray-800" src={`${theme.mode === "dark" ? "/images/landing/screens/copywriter-dark.png" : "/images/landing/screens/copywriter.png"}`} alt="" />
                            </div>
                        </div>
                    </div>
                </Container>
            </Section>
            <Section className="py-16 md:py-20 bg-slate-50 dark:bg-slate-950 overflow-hidden border-t border-gray-200 dark:border-gray-800 mt-auto">
                <Container>
                    <div className="flex flex-wrap -m-3 md:-m-4" >
                        <div className="w-full lg:w-4/12 xl:w-3/12 p-3 md:p-4">
                            <div className="pb-3">
                                <Link to="/">
                                    <Logo className="h-7" />
                                </Link>
                                <div className="mt-2 lg:mt-5">
                                    <p className="text-slate-500 dark:text-slate-300 text-base/7"> Unleash stunning visuals effortlessly with our intuitive AI.</p>
                                </div>
                            </div>
                        </div>
                        <div className="w-6/12 sm:w-3/12 lg:w-2/12 p-3 md:p-4 lg:ms-auto">
                            <h6 className="font-bold text-base text-slate-700 dark:text-white mb-3">More Tools</h6>
                            <ul>
                                <li> <Link className="inline-flex text-sm/7 text-slate-500 dark:text-slate-400 hover:text-blue-600 hover:dark:text-blue-600 transition-all">Image Generator</Link> </li>
                                <li> <Link className="inline-flex text-sm/7 text-slate-500 dark:text-slate-400 hover:text-blue-600 hover:dark:text-blue-600 transition-all">Code Generator</Link> </li>
                                <li> <Link className="inline-flex text-sm/7 text-slate-500 dark:text-slate-400 hover:text-blue-600 hover:dark:text-blue-600 transition-all">Speech to Text</Link> </li>
                                <li> <Link className="inline-flex text-sm/7 text-slate-500 dark:text-slate-400 hover:text-blue-600 hover:dark:text-blue-600 transition-all">Article Writer</Link> </li>
                                <li> <Link className="inline-flex text-sm/7 text-slate-500 dark:text-slate-400 hover:text-blue-600 hover:dark:text-blue-600 transition-all">ChatBot</Link> </li>
                            </ul>
                        </div>
                        <div className="w-6/12 sm:w-3/12 lg:w-2/12 p-3 md:p-4">
                            <h6 className="font-bold text-base text-slate-700 dark:text-white mb-3">Pages</h6>
                            <ul>
                                <li> <Link className="inline-flex text-sm/7 text-slate-500 dark:text-slate-400 hover:text-blue-600 hover:dark:text-blue-600 transition-all">Main intro</Link> </li>
                                <li> <Link className="inline-flex text-sm/7 text-slate-500 dark:text-slate-400 hover:text-blue-600 hover:dark:text-blue-600 transition-all">User Application</Link> </li>
                                <li> <Link className="inline-flex text-sm/7 text-slate-500 dark:text-slate-400 hover:text-blue-600 hover:dark:text-blue-600 transition-all">Admin Dashboard</Link> </li>
                            </ul>
                        </div>
                        <div className="w-full sm:w-6/12 lg:w-3/12 p-3 md:p-4">
                            <h6 className="font-bold text-base text-slate-700 dark:text-white mb-3">Sign up for updates</h6>
                            <div className="flex items-center gap-2">
                                <div className="relative flex-grow w-full sm:w-auto">
                                    <Input className="w-full" placeholder="name@email.com" />
                                </div>
                                <Link to="/app/templates/image" className="inline-flex justify-center font-medium text-sm bg-blue-600 text-white hover:bg-blue-800 transition-all px-3 py-2 rounded-md">
                                    <PaperAirplaneIcon className="h-5" />
                                </Link>
                            </div>
                            <p className="text-xs text-slate-500 dark:text-slate-400 mt-2">We don't share your info</p>
                        </div>
                    </div>
                </Container>
            </Section>
        </Layout>
    );
}

export default TermsPage;
